name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allow manual triggering

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.125.4" # Specify a recent Hugo version
      GO_VERSION: "1.21"    # Specify Go version for Hugo Modules
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false # Set to true if you were using git submodules for themes

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "${{ env.HUGO_VERSION }}"
          extended: true # PaperMod requires the extended version

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      
      - name: Initialize Hugo Modules and Get Theme
        run: |
          # The go.mod file should exist. If not, uncomment the next line.
          # hugo mod init github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
          hugo mod get -u github.com/adityatelange/hugo-PaperMod
          # Verify theme is downloaded
          ls -R themes/ || ls -R _vendor/ || echo "Theme not found in standard locations"

      - name: Build Hugo site
        env:
          # HUGO_ENV: production # Already set by default by actions-hugo
          # Set the base URL dynamically for GitHub Pages
          HUGO_BASEURL: "https:// ${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        run: |
          echo "Building site with baseURL: ${HUGO_BASEURL}"
          hugo --minify --baseURL "${HUGO_BASEURL}"
          # Verify public directory
          ls public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # publish_branch: gh-pages # Default is gh-pages
          # cname: example.com # Custom domain if you have one
          # force_orphan: true # Creates a new branch history every time
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Deploy Hugo site to Pages (commit ${{ github.sha }})"
